# Generated by Django 5.1.5 on 2025-04-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_internalassessment_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internalassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='internalassessment',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internal_assessments', to='school_app.exam'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='internalassessment',
            unique_together={('school_class', 'exam', 'subject', 'subsubject')},
        ),
    ]
