# Generated by Django 5.2 on 2025-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_student_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('marks_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
