# Generated by Django 5.2 on 2025-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_transferredstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferredstudent',
            old_name='transferred_at',
            new_name='transferred_on',
        ),
        migrations.AlterField(
            model_name='transferredstudent',
            name='marks_snapshot',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferredstudent',
            name='parent_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferredstudent',
            name='parent_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferredstudent',
            name='parent_phone',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
