# Generated by Django 5.1.5 on 2025-04-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_internalassessment_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalassessment',
            options={'verbose_name': 'Internal Assessment', 'verbose_name_plural': 'Internal Assessments'},
        ),
        migrations.AlterUniqueTogether(
            name='internalassessment',
            unique_together={('student', 'school_class', 'exam', 'subject', 'subsubject')},
        ),
    ]
