# Generated by Django 5.2 on 2025-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_rename_transferred_at_transferredstudent_transferred_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferredstudent',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
