# Generated by Django 5.1.5 on 2025-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_internalassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalassessment',
            name='max_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
