# Generated by Django 5.2 on 2025-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_transferredstudent_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferredstudent',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
