# Generated by Django 5.2 on 2025-05-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_transferredstudent_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITimetableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_periods', models.PositiveIntegerField(default=8)),
                ('period_duration', models.PositiveIntegerField(help_text='In minutes')),
                ('gap_between_periods', models.PositiveIntegerField(default=5, help_text='In minutes')),
                ('break_after_period_1', models.PositiveIntegerField(default=3)),
                ('break_after_period_2', models.PositiveIntegerField(default=6)),
                ('break_duration', models.PositiveIntegerField(default=15, help_text='In minutes')),
                ('start_hour', models.PositiveIntegerField(default=8)),
                ('start_minute', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AITimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher')),
                ('school_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.schoolday')),
            ],
            options={
                'ordering': ['school_day', 'period_number'],
                'unique_together': {('class_assigned', 'school_day', 'period_number')},
            },
        ),
    ]
