# Generated by Django 5.1.5 on 2025-04-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_studentattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.CreateModel(
            name='StudentSubjectRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject')),
            ],
        ),
    ]
