# Generated by Django 5.1.5 on 2025-04-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_alter_studentattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='school_app.class'),
        ),
    ]
