# Generated by Django 5.2 on 2025-05-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_aitimetablesettings_schoolday_aitimetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitimetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher'),
        ),
    ]
