# Generated by Django 5.2 on 2025-05-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_alter_aitimetableentry_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this class is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to='school_app.teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='class',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Brief overview or topics covered', null=True, verbose_name='Syllabus Overview'),
        ),
    ]
