# Generated by Django 5.1.5 on 2025-04-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_timetable_subject_timetable_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Period 5'), (6, 'Period 6'), (7, 'Period 7'), (8, 'Period 8'), (9, 'Period 9')]),
        ),
    ]
