# Generated by Django 5.1.5 on 2025-04-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalassessment',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='internalassessment',
            name='obtained_marks',
        ),
        migrations.AddField(
            model_name='internalassessment',
            name='softskill_assessment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internalassessment',
            name='syllabus_assessment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
