# Generated by Django 5.2 on 2025-05-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_absentteacher_dailytimetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituteassignment',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='school_app.teacher'),
        ),
        migrations.DeleteModel(
            name='AbsentTeacher',
        ),
    ]
