# Generated by Django 5.1.5 on 2025-04-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_remove_internalassessment_max_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillOrDevelopmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('softskill_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_development_areas', to='school_app.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_development_areas', to='school_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_development_areas', to='school_app.subject')),
            ],
            options={
                'unique_together': {('school_class', 'subject', 'student')},
            },
        ),
    ]
