# Generated by Django 5.1.5 on 2025-04-30 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_softskillperformance_syllabusperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillordevelopmentarea',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
