# Generated by Django 5.2 on 2025-05-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_schoolprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'exam', 'subject')},
        ),
        migrations.DeleteModel(
            name='ExamDate',
        ),
    ]
