# Generated by Django 5.2 on 2025-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_alter_marks_unique_together_delete_examdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='relation_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian')], default='Father', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
