# Generated by Django 5.1.5 on 2025-04-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_skillordevelopmentarea_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillordevelopmentarea',
            old_name='date',
            new_name='assessment_date',
        ),
        migrations.AlterUniqueTogether(
            name='skillordevelopmentarea',
            unique_together={('student', 'school_class', 'subject', 'assessment_date')},
        ),
    ]
