# Generated by Django 5.1.5 on 2025-05-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0018_academicyear_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.academicyear'),
        ),
    ]
